export const FETCH_POPULAR_MOVIES_REQUESTED = 'FETCH_POPULAR_MOVIES_REQUESTED';
export const FETCH_POPULAR_MOVIES_FULFILLED = 'FETCH_POPULAR_MOVIES_FULFILLED';
export const FETCH_POPULAR_MOVIES_REJECTED = 'FETCH_POPULAR_MOVIES_REJECTED';

export default {
  FETCH_POPULAR_MOVIES_REQUESTED,
  FETCH_POPULAR_MOVIES_FULFILLED,
  FETCH_POPULAR_MOVIES_REJECTED
};
