export const MOVIES_KEY = 'movies';

export const MOVIES_FETCH = 'MOVIES_FETCH';
export const MOVIES_FETCH_CANCEL = 'MOVIES_FETCH_CANCEL';
export const MOVIES_FETCH_FULFILLED = 'MOVIES_FETCH_FULFILLED';
export const MOVIES_FETCH_REJECTED = 'MOVIES_FETCH_REJECTED';

export const SET_PAGE_NUM = 'SET_PAGE_NUM';

export default {
  MOVIES_KEY,
  MOVIES_FETCH,
  MOVIES_FETCH_CANCEL,
  MOVIES_FETCH_FULFILLED,
  MOVIES_FETCH_REJECTED,
  SET_PAGE_NUM
};
