export const MOVIES_FETCH_REQUESTED = 'MOVIES_FETCH_REQUESTED';
export const MOVIES_FETCH_FULFILLED = 'MOVIES_FETCH_FULFILLED';
export const MOVIES_FETCH_REJECTED = 'MOVIES_FETCH_REJECTED';

export const SET_PAGE_NUM = 'SET_PAGE_NUM';
export const SET_FILTER = 'SET_FILTER';

export default {
  MOVIES_FETCH_REQUESTED,
  MOVIES_FETCH_FULFILLED,
  MOVIES_FETCH_REJECTED,
  SET_PAGE_NUM,
  SET_FILTER
};
