export const MOVIES_KEY = 'movies';

export const MOVIES_FETCH = 'MOVIES_FETCH';
export const MOVIES_FETCH_CANCEL = 'MOVIES_FETCH_CANCEL';
export const MOVIES_FETCH_FULFILLED = 'MOVIES_FETCH_FULFILLED';
export const MOVIES_FETCH_REJECTED = 'MOVIES_FETCH_REJECTED';

export const MOVIE_FETCH = 'MOVIE_FETCH';
export const MOVIE_FETCH_CANCEL = 'MOVIE_FETCH_CANCEL';
export const MOVIE_FETCH_FULFILLED = 'MOVIE_FETCH_FULFILLED';
export const MOVIE_FETCH_REJECTED = 'MOVIE_FETCH_REJECTED';

export default {
  MOVIES_KEY,
  MOVIES_FETCH,
  MOVIES_FETCH_CANCEL,
  MOVIES_FETCH_FULFILLED,
  MOVIES_FETCH_REJECTED
};
