export const FETCH_MOVIES_REQUESTED = 'FETCH_MOVIES_REQUESTED';
export const FETCH_POPULAR_MOVIES_FULFILLED = 'FETCH_POPULAR_MOVIES_FULFILLED';
export const FETCH_TOP_RATED_MOVIES_FULFILLED = 'FETCH_TOP_RATED_MOVIES_FULFILLED';
export const FETCH_MOVIES_REJECTED = 'FETCH_MOVIES_REJECTED';

export const SET_POPULAR_PAGE = 'SET_POPULAR_PAGE';
export const SET_TOP_RATED_PAGE = 'SET_TOP_RATED_PAGE';

export default {
  FETCH_MOVIES_REQUESTED,
  FETCH_POPULAR_MOVIES_FULFILLED,
  FETCH_TOP_RATED_MOVIES_FULFILLED,
  FETCH_MOVIES_REJECTED,
  SET_POPULAR_PAGE,
  SET_TOP_RATED_PAGE
};
