export const FETCH_POPULAR_MOVIES_REQUESTED = 'FETCH_POPULAR_MOVIES_REQUESTED';
export const FETCH_POPULAR_MOVIES_FULFILLED = 'FETCH_POPULAR_MOVIES_FULFILLED';
export const FETCH_POPULAR_MOVIES_REJECTED = 'FETCH_POPULAR_MOVIES_REJECTED';

export const FETCH_TOP_VOTED_MOVIES_REQUESTED = 'FETCH_TOP_VOTED_MOVIES_REQUESTED';
export const FETCH_TOP_VOTED_MOVIES_FULFILLED = 'FETCH_TOP_VOTED_MOVIES_FULFILLED';
export const FETCH_TOP_VOTED_MOVIES_REJECTED = 'FETCH_TOP_VOTED_MOVIES_REJECTED';

export const FETCH_TOP_REVENUE_MOVIES_REQUESTED = 'FETCH_TOP_REVENUE_MOVIES_REQUESTED';
export const FETCH_TOP_REVENUE_MOVIES_FULFILLED = 'FETCH_TOP_REVENUE_MOVIES_FULFILLED';
export const FETCH_TOP_REVENUE_MOVIES_REJECTED = 'FETCH_TOP_REVENUE_MOVIES_REJECTED';

export const EMPTY_MOVIES = 'EMPTY_MOVIES';

export default {
  FETCH_POPULAR_MOVIES_REQUESTED,
  FETCH_POPULAR_MOVIES_FULFILLED,
  FETCH_POPULAR_MOVIES_REJECTED,

  FETCH_TOP_VOTED_MOVIES_REQUESTED,
  FETCH_TOP_VOTED_MOVIES_FULFILLED,
  FETCH_TOP_VOTED_MOVIES_REJECTED,

  FETCH_TOP_REVENUE_MOVIES_REQUESTED,
  FETCH_TOP_REVENUE_MOVIES_FULFILLED,
  FETCH_TOP_REVENUE_MOVIES_REJECTED,

  EMPTY_MOVIES
};
