export const SET_MOVIE_DETAIL = 'SET_MOVIE_DETAIL';
export const EMPTY_CURRENT_MOVIE = 'EMPTY_CURRENT_MOVIE';

export const FETCH_MOVIE_DETAIL_REQUESTED = 'FETCH_MOVIE_DETAIL_REQUESTED';
export const FETCH_MOVIE_DETAIL_FULFILLED = 'FETCH_MOVIE_DETAIL_FULFILLED';
export const FETCH_MOVIE_DETAIL_REJECTED = 'FETCH_MOVIE_DETAIL_REJECTED';

export const FETCH_MOVIE_CREDITS_REQUESTED = 'FETCH_MOVIE_CREDITS_REQUESTED';
export const FETCH_MOVIE_CREDITS_FULFILLED = 'FETCH_MOVIE_CREDITS_FULFILLED';
export const FETCH_MOVIE_CREDITS_REJECTED = 'FETCH_MOVIE_CREDITS_REJECTED';

export const FETCH_MOVIE_REVIEWS_REQUESTED = 'FETCH_MOVIE_REVIEWS_REQUESTED';
export const FETCH_MOVIE_REVIEWS_FULFILLED = 'FETCH_MOVIE_REVIEWS_FULFILLED';
export const FETCH_MOVIE_REVIEWS_REJECTED = 'FETCH_MOVIE_REVIEWS_REJECTED';


export default {
  EMPTY_CURRENT_MOVIE,
  SET_MOVIE_DETAIL,
  FETCH_MOVIE_DETAIL_REQUESTED,
  FETCH_MOVIE_DETAIL_FULFILLED,
  FETCH_MOVIE_DETAIL_REJECTED,
  FETCH_MOVIE_CREDITS_REQUESTED,
  FETCH_MOVIE_CREDITS_FULFILLED,
  FETCH_MOVIE_CREDITS_REJECTED,
  FETCH_MOVIE_REVIEWS_REQUESTED,
  FETCH_MOVIE_REVIEWS_FULFILLED,
  FETCH_MOVIE_REVIEWS_REJECTED
};
