export const FETCH_MOVIE_DETAIL_REQUESTED = 'FETCH_MOVIE_DETAIL_REQUESTED';
export const FETCH_MOVIE_DETAIL_FULFILLED = 'FETCH_MOVIE_DETAIL_FULFILLED';
export const FETCH_MOVIE_DETAIL_REJECTED = 'FETCH_MOVIE_DETAIL_REJECTED';

export default {
  FETCH_MOVIE_DETAIL_REQUESTED,
  FETCH_MOVIE_DETAIL_FULFILLED,
  FETCH_MOVIE_DETAIL_REJECTED,
};
