export const FETCH_MOVIE_REQUESTED = 'FETCH_MOVIE_REQUESTED';
export const FETCH_MOVIE_FULFILLED = 'FETCH_MOVIE_FULFILLED';
export const FETCH_MOVIE_REJECTED = 'FETCH_MOVIE_REJECTED';

export default {
  FETCH_MOVIE_REQUESTED,
  FETCH_MOVIE_FULFILLED,
  FETCH_MOVIE_REJECTED,
};
