export const FETCH_POPULAR_TVSHOWS_REQUESTED = 'FETCH_POPULAR_TVSHOWS_REQUESTED';
export const FETCH_POPULAR_TVSHOWS_FULFILLED = 'FETCH_POPULAR_TVSHOWS_FULFILLED';
export const FETCH_POPULAR_TVSHOWS_REJECTED = 'FETCH_POPULAR_TVSHOWS_REJECTED';

export const FETCH_TOP_VOTED_TVSHOWS_REQUESTED = 'FETCH_TOP_VOTED_TVSHOWS_REQUESTED';
export const FETCH_TOP_VOTED_TVSHOWS_FULFILLED = 'FETCH_TOP_VOTED_TVSHOWS_FULFILLED';
export const FETCH_TOP_VOTED_TVSHOWS_REJECTED = 'FETCH_TOP_VOTED_TVSHOWS_REJECTED';

export const FETCH_LATEST_TVSHOWS_REQUESTED = 'FETCH_LATEST_TVSHOWS_REQUESTED';
export const FETCH_LATEST_TVSHOWS_FULFILLED = 'FETCH_LATEST_TVSHOWS_FULFILLED';
export const FETCH_LATEST_TVSHOWS_REJECTED = 'FETCH_LATEST_TVSHOWS_REJECTED';

export default {
  FETCH_POPULAR_TVSHOWS_REQUESTED,
  FETCH_POPULAR_TVSHOWS_FULFILLED,
  FETCH_POPULAR_TVSHOWS_REJECTED,

  FETCH_TOP_VOTED_TVSHOWS_REQUESTED,
  FETCH_TOP_VOTED_TVSHOWS_FULFILLED,
  FETCH_TOP_VOTED_TVSHOWS_REJECTED,

  FETCH_LATEST_TVSHOWS_REQUESTED,
  FETCH_LATEST_TVSHOWS_FULFILLED,
  FETCH_LATEST_TVSHOWS_REJECTED
};
