export const NAVIGATE_TO_MOVIES_SCREEN = 'NAVIGATE_TO_MOVIES_SCREEN';
export const NAVIGATE_TO_MOVIE_DETAIL_SCREEN = 'NAVIGATE_TO_MOVIE_DETAIL_SCREEN';
export const NAVIGATE_TAB = 'Navigation/NAVIGATE';
export const NAVIGATE_BACK = 'Navigation/BACK';

export default {
  NAVIGATE_TO_MOVIES_SCREEN,
  NAVIGATE_TO_MOVIE_DETAIL_SCREEN,
  NAVIGATE_TAB,
  NAVIGATE_BACK,
};
