export const NAVIGATE_TO_DRAWER_SCREEN = 'NAVIGATE_TO_DRAWER_SCREEN';
export const NAVIGATE_TO_DETAIL_SCREEN = 'NAVIGATE_TO_DETAIL_SCREEN';
export const NAVIGATE_TO_SEARCH_SCREEN = 'NAVIGATE_TO_SEARCH_SCREEN';
export const NAVIGATE_BACK = 'NAVIGATE_BACK';
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';
export const NAVIGATE_IN_DRAWER = 'NAVIGATE_IN_DRAWER';
export const DEFAULT_NAVIGATION = 'Navigation/NAVIGATE';

export default {
  NAVIGATE_TO_DRAWER_SCREEN,
  NAVIGATE_TO_DETAIL_SCREEN,
  NAVIGATE_TO_SEARCH_SCREEN,
  NAVIGATE_BACK,
  TOGGLE_DRAWER,
  NAVIGATE_IN_DRAWER,
  DEFAULT_NAVIGATION
};
