export const NAVIGATE_TO_DRAWER_SCREEN = 'NAVIGATE_TO_DRAWER_SCREEN';
export const NAVIGATE_TO_DETAIL_SCREEN = 'NAVIGATE_TO_DETAIL_SCREEN';
export const NAVIGATE_BACK = 'NAVIGATE_BACK';

export default {
  NAVIGATE_TO_DRAWER_SCREEN,
  NAVIGATE_TO_DETAIL_SCREEN,
  NAVIGATE_BACK,
};
