export const SET_KEYWORD = 'SET_KEYWORD';
export const FETCH_SEARCH_RESULT_REQUESTED = 'FETCH_SEARCH_RESULT_REQUESTED';
export const FETCH_SEARCH_RESULT_FULFILLED = 'FETCH_SEARCH_RESULT_FULFILLED';
export const FETCH_SEARCH_RESULT_REJECTED = 'FETCH_SEARCH_RESULT_REJECTED';

export default {
  SET_KEYWORD,
  FETCH_SEARCH_RESULT_REQUESTED,
  FETCH_SEARCH_RESULT_FULFILLED,
  FETCH_SEARCH_RESULT_REJECTED
};
