export const CHECK_IS_SEARCHING = 'CHECK_IS_SEARCHING';
export const FETCH_SEARCH_MOVIE_REQUESTED = 'FETCH_SEARCH_MOVIE_REQUESTED';
export const FETCH_SEARCH_MOVIE_FULFILLED = 'FETCH_SEARCH_MOVIE_FULFILLED';
export const FETCH_SEARCH_MOVIE_REJECTED = 'FETCH_SEARCH_MOVIE_REJECTED';
export const RESET_MOVIES = 'RESET_MOVIES';
export const RESET_PAGE = 'RESET_PAGE';

export default {
  CHECK_IS_SEARCHING,
  FETCH_SEARCH_MOVIE_REQUESTED,
  FETCH_SEARCH_MOVIE_FULFILLED,
  FETCH_SEARCH_MOVIE_REJECTED,
  RESET_MOVIES,
  RESET_PAGE
};
