export const IS_SEARCHING = 'IS_SEARCHING';
export const FETCH_SEARCH_MOVIE_REQUESTED = 'FETCH_SEARCH_MOVIE_REQUESTED';
export const FETCH_SEARCH_MOVIE_FULFILLED = 'FETCH_SEARCH_MOVIE_FULFILLED';
export const FETCH_SEARCH_MOVIE_REJECTED = 'FETCH_SEARCH_MOVIE_REJECTED';
export const EMPTY_SEARCH_MOVIES = 'EMPTY_SEARCH_MOVIES';

export default {
  IS_SEARCHING,
  FETCH_SEARCH_MOVIE_REQUESTED,
  FETCH_SEARCH_MOVIE_FULFILLED,
  FETCH_SEARCH_MOVIE_REJECTED,
  EMPTY_SEARCH_MOVIES,
};
