export const SET_TV_SHOW_DETAIL = 'SET_TV_SHOW_DETAIL';
export const EMPTY_CURRENT_TV_SHOW = 'EMPTY_CURRENT_TV_SHOW';

export const FETCH_TV_SHOW_DETAIL_REQUESTED = 'FETCH_TV_SHOW_DETAIL_REQUESTED';
export const FETCH_TV_SHOW_DETAIL_FULFILLED = 'FETCH_TV_SHOW_DETAIL_FULFILLED';
export const FETCH_TV_SHOW_DETAIL_REJECTED = 'FETCH_TV_SHOW_DETAIL_REJECTED';

export const FETCH_TV_SHOW_CREDITS_REQUESTED = 'FETCH_TV_SHOW_CREDITS_REQUESTED';
export const FETCH_TV_SHOW_CREDITS_FULFILLED = 'FETCH_TV_SHOW_CREDITS_FULFILLED';
export const FETCH_TV_SHOW_CREDITS_REJECTED = 'FETCH_TV_SHOW_CREDITS_REJECTED';

export default {
  EMPTY_CURRENT_TV_SHOW,
  SET_TV_SHOW_DETAIL,
  FETCH_TV_SHOW_DETAIL_REQUESTED,
  FETCH_TV_SHOW_DETAIL_FULFILLED,
  FETCH_TV_SHOW_DETAIL_REJECTED,
  FETCH_TV_SHOW_CREDITS_REQUESTED,
  FETCH_TV_SHOW_CREDITS_FULFILLED,
  FETCH_TV_SHOW_CREDITS_REJECTED
};
