export const GET_POPULAR_PERSON_PROFILES = 'GET_POPULAR_PERSON_PROFILES';
export const GET_MOVIE_BACKDROPS_OF_PERSON = 'GET_MOVIE_BACKDROPS_OF_PERSON';

export const FETCH_POPULAR_PEOPLE_REQUESTED = 'FETCH_POPULAR_PEOPLE_REQUESTED';
export const FETCH_POPULAR_PEOPLE_FULFILLED = 'FETCH_POPULAR_PEOPLE_FULFILLED';
export const FETCH_POPULAR_PEOPLE_REJECTED = 'FETCH_POPULAR_PEOPLE_REJECTED';

export default {
  GET_POPULAR_PERSON_PROFILES,
  GET_MOVIE_BACKDROPS_OF_PERSON,

  FETCH_POPULAR_PEOPLE_REQUESTED,
  FETCH_POPULAR_PEOPLE_FULFILLED,
  FETCH_POPULAR_PEOPLE_REJECTED,
};

