export const GET_POPULAR_PERSON_BACKDROPS = 'GET_POPULAR_PERSON_BACKDROPS';

export const FETCH_POPULAR_PEOPLE_REQUESTED = 'FETCH_POPULAR_PEOPLE_REQUESTED';
export const FETCH_POPULAR_PEOPLE_FULFILLED = 'FETCH_POPULAR_PEOPLE_FULFILLED';
export const FETCH_POPULAR_PEOPLE_REJECTED = 'FETCH_POPULAR_PEOPLE_REJECTED';

export default {
  GET_POPULAR_PERSON_BACKDROPS,

  FETCH_POPULAR_PEOPLE_REQUESTED,
  FETCH_POPULAR_PEOPLE_FULFILLED,
  FETCH_POPULAR_PEOPLE_REJECTED,
};

